#!/usr/bin/env python3
from __future__ import annotations
import argparse,json,shutil,subprocess,sys
from pathlib import Path
ROOT=Path(__file__).resolve().parents[2];sys.path.insert(0,str(ROOT/'src'))
from portable_ai_governance.supply_chain.signing import generate_ed25519_keypair,sign_blob
from portable_ai_governance.asset_security.common import M23_BASELINE_COMMIT,M23_BASELINE_TAG,M24_VERSION,sha256_file,write_json
from portable_ai_governance.asset_security.inventory import require_registered_asset
from portable_ai_governance.asset_security.lifecycle import validate_sanitization_record
from portable_ai_governance.asset_security.dlp import authorize_export
from portable_ai_governance.asset_security.evaluation import evaluate_m24_policy
SOURCE_FILES=['governance/enterprise/m24/asset-security-policy.json','governance/enterprise/m24/asset-register.json','governance/enterprise/m24/data-lifecycle-policy.json','governance/enterprise/m24/dlp-policy.json','governance/enterprise/m24/cryptographic-lifecycle-policy.json','governance/enterprise/m24/m24-control-mapping.json','governance/enterprise/m24/m24-gap-closure.json','governance/controls/control-catalog.json','governance/mappings/framework-mapping.json','src/portable_ai_governance/asset_security/__init__.py','src/portable_ai_governance/asset_security/common.py','src/portable_ai_governance/asset_security/inventory.py','src/portable_ai_governance/asset_security/lifecycle.py','src/portable_ai_governance/asset_security/dlp.py','src/portable_ai_governance/asset_security/crypto_lifecycle.py','src/portable_ai_governance/asset_security/evaluation.py','src/portable_ai_governance/asset_security/runtime.py','scripts/m24/build_m24_material.py','scripts/m24/validate_m24_node.py','scripts/m24/validate_m24_local.sh','scripts/m24/validate_m24_regression.sh','scripts/m24/verify_node1.sh','scripts/m24/verify_node2.sh','scripts/m24/ci_validate.sh','deploy/m24/deploy_node.sh','deploy/m24/one_shot_node1.sh','deploy/m24/one_shot_node2.sh','deploy/m24/package_verifier_material.sh','tests/asset_security/test_m24_asset_security.py','.github/workflows/m24-asset-data.yml','pyproject.toml','.gitignore']
SOURCE_FILES += ['README.md','instruction.md']+sorted(str(p.relative_to(ROOT)) for p in (ROOT/'docs').glob('*.md'));SOURCE_FILES=list(dict.fromkeys(SOURCE_FILES))
def J(p):return json.loads((ROOT/p).read_text())
def main():
 ap=argparse.ArgumentParser();ap.add_argument('--out',required=True);a=ap.parse_args();out=Path(a.out);shutil.rmtree(out,ignore_errors=True);out.mkdir(parents=True)
 copies={'governance/enterprise/m24/asset-security-policy.json':'asset-security-policy.json','governance/enterprise/m24/asset-register.json':'asset-register.json','governance/enterprise/m24/data-lifecycle-policy.json':'data-lifecycle-policy.json','governance/enterprise/m24/dlp-policy.json':'dlp-policy.json','governance/enterprise/m24/cryptographic-lifecycle-policy.json':'cryptographic-lifecycle-policy.json','governance/enterprise/m24/m24-control-mapping.json':'m24-control-mapping.json','governance/enterprise/m24/m24-gap-closure.json':'m24-gap-closure.json'}
 for src,name in copies.items():shutil.copy2(ROOT/src,out/name);(out/name).chmod(0o600)
 priv=out/'signing-private.pem';pub=out/'signing-public.pem';generate_ed25519_keypair(priv,pub)
 now=1700000000;lifecycle=J('governance/enterprise/m24/data-lifecycle-policy.json');dlp=J('governance/enterprise/m24/dlp-policy.json');assets=J('governance/enterprise/m24/asset-register.json')
 sanitize={'record_id':'m24-sanitize-positive','asset_id':'pag-governance-evidence','performed_at':now,'performed_by':'m24-validation','approved_by':'m24-security-officer','method':'crypto-erase','classification':'restricted','evidence_sha256':'0'*64};validate_sanitization_record(sanitize,lifecycle);write_json(out/'positive-sanitization-record.json',sanitize)
 asset=require_registered_asset(assets,'pag-node1-control-plane');decision=authorize_export({'actor':'m24-operator','approved_by':'m24-security-officer','destination':'enterprise-secure-exchange','purpose':'validated support transfer','encrypted':True},asset,dlp,'non-sensitive validation payload');write_json(out/'positive-export-decision.json',decision)
 controls=J('governance/controls/control-catalog.json');ev=evaluate_m24_policy(J('governance/enterprise/m24/asset-security-policy.json'),assets,lifecycle,dlp,J('governance/enterprise/m24/cryptographic-lifecycle-policy.json'),controls,now)
 summary={'ok':ev['ok'],'validation_time':now,'policy':ev,'positive_tests':{'registered_assets':len(assets['assets']),'sanitization_record':True,'controlled_export':decision['decision']=='allow'},'negative_tests_required':['unregistered asset rejected','legal hold blocks disposal','restricted sanitization without approval rejected','unapproved export destination rejected','unencrypted sensitive export rejected','self-approved export rejected','sensitive-pattern export rejected','overdue active key rejected']};write_json(out/'m24-validation-summary.json',summary)
 write_json(out/'m24-source-manifest.json',{'version':M24_VERSION,'parent_baseline_commit':M23_BASELINE_COMMIT,'parent_baseline_tag':M23_BASELINE_TAG,'source_binding':'content_digest_allows_precommit_validation_without_claiming_uncommitted_tree_is_a_release','files':{p:sha256_file(ROOT/p) for p in SOURCE_FILES}})
 protected=list(copies.values())+['m24-validation-summary.json','m24-source-manifest.json','signing-public.pem','positive-sanitization-record.json','positive-export-decision.json'];head=subprocess.run(['git','-c',f'safe.directory={ROOT}','-C',str(ROOT),'rev-parse','HEAD'],capture_output=True,text=True,check=True).stdout.strip();policy=J('governance/enterprise/m24/asset-security-policy.json')
 manifest={'version':M24_VERSION,'milestone':'M24','title':'Asset Security, Data Protection & Cryptographic/Data Lifecycle','m23_baseline_commit':M23_BASELINE_COMMIT,'m23_baseline_tag':M23_BASELINE_TAG,'repository_head_at_generation':head,'source_binding':'m24-source-manifest.json content digests','artifacts':{n:sha256_file(out/n) for n in protected},'boundaries':{'historical_m0_m23_immutable':True,'node1_data_control_authority':True,'node2_verifier_only':True,'validation_private_keys_are_non_production':True,'m21_platform_gaps_not_overridden':True},'claim_boundaries':policy['claim_boundaries'],'evaluation':summary};write_json(out/'m24-asset-data-manifest.json',manifest);sign_blob(out/'m24-asset-data-manifest.json',priv,out/'m24-asset-data-manifest.json.sig');print(json.dumps({'ok':summary['ok'],'out':str(out),'m23_baseline':M23_BASELINE_COMMIT},indent=2))
if __name__=='__main__':main()
