#!/usr/bin/env python3
import argparse,json,os,shutil,subprocess,sys
from pathlib import Path
ROOT=Path(__file__).resolve().parents[2];sys.path.insert(0,str(ROOT/'src'))
from portable_ai_governance.platform_security.common import write_json,sha256_file
from portable_ai_governance.platform_security.evaluation import evaluate_profiles
from portable_ai_governance.platform_security.firmware import make_descriptor,sign_descriptor,evaluate_update
from portable_ai_governance.platform_security.dice import derive_cdi_demo
from portable_ai_governance.supply_chain.signing import generate_ed25519_keypair,sign_blob
from portable_ai_governance.action_agent.common import secure_tree
ap=argparse.ArgumentParser();ap.add_argument('--node1-profile',required=True);ap.add_argument('--node2-profile',required=True);ap.add_argument('--out',required=True);a=ap.parse_args();os.umask(0o077);out=Path(a.out).resolve();out.mkdir(parents=True,exist_ok=True,mode=0o700)
for rel,name in [('governance/platform/m21/platform-security-policy.json','platform-security-policy.json'),('governance/platform/m21/m21-control-mapping.json','m21-control-mapping.json'),('governance/platform/m21/threat-model.json','threat-model.json'),('governance/platform/m21/key-management-policy.json','key-management-policy.json'),('governance/platform/m21/measured-boot-policy.json','measured-boot-policy.json')]:shutil.copy2(ROOT/rel,out/name);os.chmod(out/name,0o600)
for src,name in [(a.node1_profile,'node1-platform-profile.json'),(a.node2_profile,'node2-platform-profile.json')]:shutil.copy2(src,out/name);os.chmod(out/name,0o600)
n1=json.loads((out/'node1-platform-profile.json').read_text());n2=json.loads((out/'node2-platform-profile.json').read_text());pol=json.loads((out/'platform-security-policy.json').read_text());write_json(out/'platform-validation-summary.json',evaluate_profiles(n1,n2,pol))
shutil.copy2(ROOT/'tests/fixtures/m21/firmware.bin',out/'firmware.bin');os.chmod(out/'firmware.bin',0o600);generate_ed25519_keypair(out/'signing-private.pem',out/'signing-public.pem');desc=make_descriptor(out/'firmware.bin','PAG-M21-DEMO-FW','3.0.0',3,out/'firmware-descriptor.json');sign_descriptor(out/'firmware-descriptor.json',out/'signing-private.pem',out/'firmware-descriptor.json.sig');write_json(out/'rollback-positive.json',evaluate_update('2.0.0',2,desc));write_json(out/'rollback-negative.json',evaluate_update('4.0.0',4,desc))
dice={'mode':'DEMONSTRATION_ONLY','hardware_dice_claim':False,'first_mutable_code_sha256':sha256_file(out/'firmware.bin'),'cdi_sha256':derive_cdi_demo('11'*32,sha256_file(out/'firmware.bin'),'PAG-M21'),'note':'Software derivation demonstrates DICE semantics only; hardware DICE must be evidenced by the platform.'};write_json(out/'dice-demo.json',dice)
for rel,name in [('examples/m21/systemd/pag-platform-demo.service','pag-platform-demo.service'),('examples/m21/apparmor/usr.bin.pag-platform-demo','apparmor-profile'),('examples/m21/selinux/pag_platform_demo.te','selinux-policy.te')]:shutil.copy2(ROOT/rel,out/name);os.chmod(out/name,0o600)
names=['platform-security-policy.json','m21-control-mapping.json','threat-model.json','key-management-policy.json','measured-boot-policy.json','pag-platform-demo.service','apparmor-profile','selinux-policy.te','node1-platform-profile.json','node2-platform-profile.json','platform-validation-summary.json','firmware.bin','firmware-descriptor.json','firmware-descriptor.json.sig','rollback-positive.json','rollback-negative.json','dice-demo.json','signing-public.pem']
head=subprocess.run(['git','-c',f'safe.directory={ROOT}','-C',str(ROOT),'rev-parse','HEAD'],capture_output=True,text=True).stdout.strip()
man={'version':'0.21.0','milestone':'M21','purpose':'Embedded Linux & Platform Security Validation','m20_commit':head,'artifacts':{n:sha256_file(out/n) for n in names},'boundaries':pol['boundaries']};write_json(out/'m21-platform-manifest.json',man);sign_blob(out/'m21-platform-manifest.json',out/'signing-private.pem',out/'m21-platform-manifest.json.sig');secure_tree(out);print(f'PASS: M21 platform-security material generated at {out}');print(f"PASS: validation_mode={json.loads((out/'platform-validation-summary.json').read_text())['validation_mode']}")
