#!/usr/bin/env python3
from __future__ import annotations
import argparse,json,shutil,subprocess,sys
from pathlib import Path
ROOT=Path(__file__).resolve().parents[2];sys.path.insert(0,str(ROOT/'src'))
from portable_ai_governance.supply_chain.signing import generate_ed25519_keypair,sign_blob
from portable_ai_governance.operational_security.common import M25_BASELINE_COMMIT,M25_BASELINE_TAG,M26_VERSION,sha256_file,write_json
from portable_ai_governance.operational_security.soc import normalize_event,correlate
from portable_ai_governance.operational_security.vulnerability import assess_finding
from portable_ai_governance.operational_security.incident import run_playbook
from portable_ai_governance.operational_security.backup import make_backup_record,verify_restore
from portable_ai_governance.operational_security.evaluation import evaluate_m26_policy
SOURCE_FILES=['governance/enterprise/m26/soc-policy.json','governance/enterprise/m26/vulnerability-operations-policy.json','governance/enterprise/m26/incident-response-policy.json','governance/enterprise/m26/backup-dr-policy.json','governance/enterprise/m26/m26-control-mapping.json','governance/enterprise/m26/m26-gap-closure.json','governance/controls/control-catalog.json','governance/mappings/framework-mapping.json','src/portable_ai_governance/operational_security/__init__.py','src/portable_ai_governance/operational_security/common.py','src/portable_ai_governance/operational_security/soc.py','src/portable_ai_governance/operational_security/vulnerability.py','src/portable_ai_governance/operational_security/incident.py','src/portable_ai_governance/operational_security/backup.py','src/portable_ai_governance/operational_security/evaluation.py','src/portable_ai_governance/operational_security/runtime.py','tests/operational_security/test_m26_operational_security.py','.github/workflows/m26-operational-security.yml','pyproject.toml','.gitignore']
SOURCE_FILES += [str(p.relative_to(ROOT)) for p in sorted((ROOT/'scripts/m26').glob('*'))]+[str(p.relative_to(ROOT)) for p in sorted((ROOT/'deploy/m26').glob('*'))]+['README.md','instruction.md']+sorted(str(p.relative_to(ROOT)) for p in (ROOT/'docs').glob('*.md'));SOURCE_FILES=list(dict.fromkeys(SOURCE_FILES))
def J(p):return json.loads((ROOT/p).read_text())
def main():
 ap=argparse.ArgumentParser();ap.add_argument('--out',required=True);a=ap.parse_args();out=Path(a.out);shutil.rmtree(out,ignore_errors=True);out.mkdir(parents=True)
 copies={f'governance/enterprise/m26/{x}':x for x in ['soc-policy.json','vulnerability-operations-policy.json','incident-response-policy.json','backup-dr-policy.json','m26-control-mapping.json','m26-gap-closure.json']}
 for src,name in copies.items():shutil.copy2(ROOT/src,out/name);(out/name).chmod(0o600)
 priv=out/'signing-private.pem';pub=out/'signing-public.pem';generate_ed25519_keypair(priv,pub)
 soc=J('governance/enterprise/m26/soc-policy.json');vp=J('governance/enterprise/m26/vulnerability-operations-policy.json');irp=J('governance/enterprise/m26/incident-response-policy.json');bp=J('governance/enterprise/m26/backup-dr-policy.json');controls=J('governance/controls/control-catalog.json')
 raw=[{'event_id':'evt-1','event_type':'denied_flow','severity':'high','source':'m25-network','subject':'node2','timestamp':100},{'event_id':'evt-2','event_type':'unauthorized_egress','severity':'critical','source':'m25-network','subject':'node1','timestamp':120}];events=[normalize_event(e,soc) for e in raw];alerts=correlate(events,soc);write_json(out/'soc-normalized-events.json',events);write_json(out/'soc-correlation-alerts.json',alerts)
 fs=[{'finding_id':'CVE-DEMO-CRIT','component':'demo-lib','severity':'critical','detected_at':0,'known_exploited':False,'owner':'psirt','status':'open'},{'finding_id':'CVE-DEMO-KEV','component':'demo-agent','severity':'medium','detected_at':3500,'known_exploited':True,'owner':'psirt','status':'open'}];ass=[assess_finding(x,vp,100000) for x in fs];write_json(out/'vulnerability-assessments.json',ass)
 inc=run_playbook({'incident_id':'inc-demo-001','status':'detected','severity':'critical'},irp,irp['required_steps']);write_json(out/'incident-playbook-result.json',inc)
 data=b'portable-agentic-ai-governance critical control database snapshot';br=make_backup_record('control-db',data,bp,1000);rr=verify_restore(br,data,2000,5600,bp,1000);write_json(out/'backup-record.json',br);write_json(out/'restore-test-report.json',rr)
 ev=evaluate_m26_policy(soc,vp,irp,bp,controls);summary={'ok':ev['ok'] and len(alerts)==1 and all(x['remediation_due'] for x in ass) and inc['final_status']=='closed' and rr['ok'],'policy':ev,'soc_alert_count':len(alerts),'vulnerability_due_count':sum(x['remediation_due'] for x in ass),'incident_final_status':inc['final_status'],'restore_ok':rr['ok'],'validation_mode':'NON_DESTRUCTIVE_SIMULATED_OPERATIONAL_EVIDENCE'};write_json(out/'m26-validation-summary.json',summary)
 write_json(out/'m26-source-manifest.json',{'version':M26_VERSION,'parent_baseline_commit':M25_BASELINE_COMMIT,'parent_baseline_tag':M25_BASELINE_TAG,'source_binding':'content_digest_allows_precommit_validation_without_claiming_uncommitted_tree_is_a_release','files':{p:sha256_file(ROOT/p) for p in SOURCE_FILES}})
 protected=list(copies.values())+['m26-validation-summary.json','m26-source-manifest.json','soc-normalized-events.json','soc-correlation-alerts.json','vulnerability-assessments.json','incident-playbook-result.json','backup-record.json','restore-test-report.json','signing-public.pem'];head=subprocess.run(['git','-c',f'safe.directory={ROOT}','-C',str(ROOT),'rev-parse','HEAD'],capture_output=True,text=True,check=True).stdout.strip()
 manifest={'version':M26_VERSION,'milestone':'M26','title':'SOC, Vulnerability, Incident Response, Immutable Backup & Disaster Recovery','m25_baseline_commit':M25_BASELINE_COMMIT,'m25_baseline_tag':M25_BASELINE_TAG,'repository_head_at_generation':head,'source_binding':'m26-source-manifest.json content digests','artifacts':{n:sha256_file(out/n) for n in protected},'boundaries':{'historical_m0_m25_immutable':True,'node1_operational_authority':True,'node2_verifier_only':True,'validation_does_not_modify_live_soc_or_backup_infrastructure':True,'external_siem_backup_platform_integration_is_deployment_specific':True},'claim_boundaries':bp['claim_boundaries'],'evaluation':summary};write_json(out/'m26-ops-manifest.json',manifest);sign_blob(out/'m26-ops-manifest.json',priv,out/'m26-ops-manifest.json.sig');print(json.dumps({'ok':summary['ok'],'out':str(out),'m25_baseline':M25_BASELINE_COMMIT},indent=2))
if __name__=='__main__':main()
